name: Development Builds

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Releasing for macOS
      run: dotnet publish -c Release -r osx-x64 --self-contained true
    - name: Releasing for Linux
      run: dotnet publish -c Release -r linux-x64 --self-contained true
    - name: Releasing for Windows
      run: dotnet publish -c Release -r win-x64 --self-contained true; ls -lacs ./bin/Release
    - uses: actions/checkout@v2
    - uses: papeloto/action-zip@v1
      with:
          files: ./bin/Release/net5.0
          dest: ./binaries.zip
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: ./binaries.zip
